# -*- coding: utf-8 -*-
"""Ecommerce_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12llJmt70Iag_E4Wu88tvGPj8ajZkjEO5
"""

import pandas as pd
df = pd.read_csv("ecommerce.csv", encoding="latin1")

df.shape

df.info()

df.head()

#This data contains transactional data from an ecommerce store which has 9994 rows and 21 columns including 6 numeric features and 15 categorical (object) features.

df['Order Date'] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df["Shipping_Delay"] = (df["Ship Date"] - df["Order Date"]).dt.days

df.isnull().sum()

df.duplicated().sum()

df[["Sales","Profit","Discount","Quantity"]].describe()

df[["Sales","Profit","Discount","Quantity"]].median()

(df["Profit"] < 0).sum()

df[df["Profit"] < 0][["Sales", "Discount", "Quantity"]].describe()

#A significant portion of loss-making transactions are driven by high discounting on relatively low-quantity orders, indicating inefficient discount strategies.

"""**EDA**"""

#Sales vs Profit chart
import matplotlib.pyplot as plt

plt.figure()
plt.scatter(df["Sales"], df["Profit"], alpha=0.5)
plt.axhline(0)
plt.xlabel("Sales")
plt.ylabel("Profit")
plt.title("Sales vs Profit")
plt.show()

"""The analysis shows that higher sales do not necessarily refers into higher profit. Several high-sales transactions result in losses, mainly due to inefficient discounting strategies. Most profitable transactions are saturated within a moderate sales range (approximately 0–5,000), indicatingg that controlled pricing and discounting results in
 profitability more effectively than high sales volume alone.
"""

#Discount Impact on Profit
plt.figure()
plt.scatter(df["Discount"], df["Profit"], alpha=0.5)
plt.axhline(0)
plt.xlabel("Discount")
plt.ylabel("Profit")
plt.title("Discount vs Profit")
plt.show()

"""Profit declines sharply as discount rates increase. Transactions with discounts exceeding 40–50% are loss-making or yield minimal profit. products discounted within the 0–20% range generate the highest profits, suggesting that moderate discounting is optimal for maintaining profitability."""

#Profit by Category

df.groupby("Category")["Profit"].mean().plot(kind="bar")
plt.ylabel("Average Profit")
plt.title("Average Profit by Product Category")
plt.show()

"""The Technology category exhibits the highest average profit,majorly outperforming Office Supplies and Furniture. This indicates that technology products offer stronger margins and represent a main revenue opportunity for the store/business
.
"""

#Profit by subcategory
df.groupby("Sub-Category")["Profit"].mean().sort_values().head(10)

"""Among sub-categories, Tables (under Furniture category) contribute the highest average losses, while Copiers (under Technology category) generate the highest average profit. This suggests that pricing, discounting, or cost structures for tables may require reassessment, while copiers represent a high-value product line in the data
.

Feature **Engineering**
"""

df["High_Discount"] = (df["Discount"] >= 0.4).astype(int)
df["Is_Loss"] = (df["Profit"] < 0).astype(int)

df['Order_Month'] = df['Order Date'].dt.month

"""The columns Row ID,Order ID,Customer ID,Product Name,City,State can be deleted to prevent overfitting(these columns have high cardinality)."""

model_df = df[["Profit",
        "Sales",
        "Quantity",
        "Discount",
        "Shipping_Delay",
        "High_Discount",
        "Order_Month",
        "Category",
        "Sub-Category",
        "Region",
        "Segment",
        "Ship Mode"]]

model_df = pd.get_dummies(
    model_df,
    columns=["Category", "Sub-Category", "Region", "Segment", "Ship Mode"],
    drop_first=True
)

X = model_df.drop("Profit", axis=1)
y = model_df["Profit"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state= 42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train.shape, X_test.shape

X_train.isna().sum().sum()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
mae_lr = mean_absolute_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

rmse_lr, mae_lr, r2_lr



from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(
    random_state=42,
    max_depth=6  # prevents overfitting
)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))
mae_dt = mean_absolute_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

rmse_dt, mae_dt, r2_dt



from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    max_depth=8,
    n_jobs=-1
)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

rmse_rf, mae_rf, r2_rf



results = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree", "Random Forest"],
    "RMSE": [rmse_lr, rmse_dt, rmse_rf],
    "MAE": [mae_lr, mae_dt, mae_rf],
    "R2": [r2_lr, r2_dt, r2_rf]
})

results

"""Random Forest performs best among the tested models, reducing average prediction error significantly compared to linear and tree-based baselines.

Linear regression and Decision tree didnt worked up to the mark as Profit is influenced by many external and unobserved factors such as supplier costs, operational expenses, and return rates, which are not present in the dataset i performed feature enginerring on. As a result, while discounting and category information provide some signal, the overall variance in profit remains difficult to explain at a transaction level .

**Business** **Recommendations** i would suggest from my findings,
1. Re-evaluate High Discount Strategies
   as transactions with discounts above 40–50% consistently result in negative or near-zero profit.

2. Focus on High-Margin Product Categories
   Technology category generates the highest average profit, with sub-categories like Copiers performing exceptionally good.

3. Address Loss-Making Sub-Categories
   as i found that Tables (Furniture) consistently show negative average profit, so this needs a constant check.

4. Optimize Discounting Based on Order Size
   Few Loss-making orders often involve high discounts on low-quantity purchases.

5. Use ML Models as Decision Support, Not Automation
   Profit prediction is noisy and messy too due to missing operational cost factors, limiting model precision.
"""

